import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Navbar from "../components/Navbar";
import Footer from "@/components/footer";
import Musics from "@/components/Musics";
import { SessionManager } from "@/utils/session-manager";
import { useEffect } from "react";

export default function Home() {
  useEffect(() => {
    const loggedIn = SessionManager.hasToken();
    if (!loggedIn) {
      SessionManager.redirect("/login");
    }
  }, []);
  return (
    <>
      <Head>
        <title>CanaStream</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <main className={styles.main} style={{ backgroundColor: "#101C27" }}>
          <Navbar />

          <Musics />

          <Footer />
        </main>
      </div>
    </>
  );
}
